### ISSUE TITLE
Wrong gradle depencency in README

### ISSUE THREAD

**Issue by PatrickMA** [glomadrian/loading-balls#1]
You have a wrong gradle depencency in your readme:

```
  compile 'com.github.glomadrian:loading-balls:1.1@aar'
```

It should be (according to your maven repository):

```
compile 'com.github.glomadrian:loadingballs:1.1@aar'
```

-> without the dash between "loading" and "balls".

**Comment by Odaym** [comment]
correct, please edit the file, wasted some time here :)

Good work, I love the performance and it's really beautiful, going over the code tomorrow

**Comment by glomadrian** [comment]
Solved, thanks for the feedback.
